export interface Env{DB:D1Database;ASSETS:Fetcher}
type Entry={className:string;subject:string;teacher:string;room:string;slotId:string}
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","access-control-allow-origin":"*"}})
async function active(env:Env){return env.DB.prepare("select id,academic_year_id,status from schedule_versions where status='active' order by created_at desc limit 1").first<any>()}
async function entries(env:Env,versionId:string){const r=await env.DB.prepare("select slot_id as slotId,class_name as className,subject_name as subject,teacher_name as teacher,room_name as room from schedule_entries where schedule_version_id=? order by slot_id,class_name").bind(versionId).all<Entry>();return r.results||[]}
function conflicts(es:Entry[]){const out:string[]=[];const seen=new Set<string>();for(const e of es){for(const k of ["slotId|className","slotId|teacher","slotId|room"]){const v=k==="slotId|className"?e.slotId+"|"+e.className:k==="slotId|teacher"?e.slotId+"|"+e.teacher:e.slotId+"|"+e.room;if(seen.has(k+"|"+v))out.push(v);seen.add(k+"|"+v)}}return [...new Set(out)]}
export default{async fetch(req:Request,env:Env):Promise<Response>{try{const u=new URL(req.url)
if(u.pathname==="/api/health")return json({ok:true,service:"sakala-pro"})
if(u.pathname==="/api/bootstrap"){const v=await active(env);const es=v?await entries(env,v.id):[];return json({version:v,schedule:{entries:es},conflicts:conflicts(es)})}
if(u.pathname==="/api/schedule/preview"&&req.method==="POST"){const body=await req.json().catch(()=>({})) as {entries?:Entry[]};const v=await active(env);const es=body.entries|| (v?await entries(env,v.id):[]);return json({baseVersionId:v?.id||null,entries:es,conflicts:conflicts(es)})}
if(u.pathname==="/api/schedule/impact"&&req.method==="POST"){const body=await req.json().catch(()=>({})) as {entries?:Entry[]};const v=await active(env);const current=v?await entries(env,v.id):[];const next=body.entries||current;const key=(e:Entry)=>[e.slotId,e.className,e.subject,e.teacher,e.room].join("|");const a=new Set(current.map(key)),b=new Set(next.map(key));return json({baseVersionId:v?.id||null,added:[...b].filter(x=>!a.has(x)).length,removed:[...a].filter(x=>!b.has(x)).length,changed:0,conflicts:conflicts(next)})}
if(u.pathname==="/api/schedule/apply"&&req.method==="POST"){const body=await req.json() as {baseVersionId?:string;entries?:Entry[]};if(!body.baseVersionId||!Array.isArray(body.entries))return json({ok:false,error:"baseVersionId and entries are required"},400);const v=await active(env);if(!v||v.id!==body.baseVersionId)return json({ok:false,error:"Active schedule changed; refresh and preview again."},409);const bad=conflicts(body.entries);if(bad.length)return json({ok:false,error:"Schedule contains conflicts",conflicts:bad},409);const id=crypto.randomUUID(),now=new Date().toISOString();const statements=[env.DB.prepare("update schedule_versions set status='archived' where id=?").bind(v.id),env.DB.prepare("insert into schedule_versions(id,academic_year_id,status,created_at) values(?,?,?,?)").bind(id,v.academic_year_id,"active",now)];for(let i=0;i<body.entries.length;i++){const e=body.entries[i];statements.push(env.DB.prepare("insert into schedule_entries(id,schedule_version_id,slot_id,class_name,subject_name,teacher_name,room_name) values(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,e.slotId,e.className,e.subject,e.teacher,e.room))}statements.push(env.DB.prepare("insert into history_events(id,entity_type,entity_id,event_type,payload_json,created_at) values(?,?,?,?,?,?)").bind(crypto.randomUUID(),"schedule_version",id,"applied",JSON.stringify({baseVersionId:v.id,count:body.entries.length}),now));await env.DB.batch(statements);return json({ok:true,versionId:id,count:body.entries.length})}
if(u.pathname.startsWith("/api/"))return json({error:"Not found"},404);return env.ASSETS.fetch(req)}catch(e){return json({error:e instanceof Error?e.message:"Internal error"},500)}}}